name: Security Check

on:
  push:
    branches:
      - '*'

jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1

      # Run the CodeQL analysis
      - name: Run CodeQL analysis
        uses: github/codeql-action/analyze@v1
