name: Test

on:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    #services:
    #  postgres:
    #    image: postgres:latest
    #    alias: localhost

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts'
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Run test
        run: pnpm test
      # Generate code coverage report
      - name: Generate code coverage report
        run: pnpm test:cov

      # Upload code coverage artifacts
      - name: Upload code coverage artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage/
      
      # Set the coverage percentage as an output
      - name: Set coverage output
        id: coverage
        run: |
          coverage=$(awk '/^All files[\s\S]*?(\d+\.\d+%)/ { print $1 }' coverage/summary.txt)
          echo "::set-output name=coverage::$coverage"

